apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secretproviderclass
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    userAssignedIdentityID: ""  # Set the clientID of the user-assigned managed identity to use
    keyvaultName: ""               # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: ""           # keyvault secret name
          objectType: 
    tenantId: ""                # The tenant ID of the key vault